CREATE TABLE oauth_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pkce_challenge TEXT NOT NULL,
    pkce_verifier TEXT NOT NULL,
    csrf_state TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);
